import{a as S,S as q,i as l}from"./assets/vendor-BLPZKqeQ.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const B="50507982-c6a73d82cfbe0bce0234dfd9b",$="https://pixabay.com/api/";async function f(o,t){return(await S.get($,{params:{key:B,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const m=document.querySelector(".gallery"),y=document.querySelector(".loader"),h=document.querySelector(".load-more"),M=new q(".gallery a",{captionsData:"alt",captionDelay:250});function p(o){const t=o.map(({webformatURL:a,largeImageURL:i,tags:e,likes:r,views:n,comments:w,downloads:v})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${i}">
        <img class="gallery-image" src="${a}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${r}</p>
        <p><b>Views:</b> ${n}</p>
        <p><b>Comments:</b> ${w}</p>
        <p><b>Downloads:</b> ${v}</p>
      </div>
    </li>`).join("");m.insertAdjacentHTML("beforeend",t),M.refresh()}function O(){m.innerHTML=""}function g(){y.classList.remove("hidden")}function b(){y.classList.add("hidden")}function L(){h.classList.remove("hidden")}function d(){h.classList.add("hidden")}const E=document.querySelector("#search-form"),H=document.querySelector("#load-more");let c="",s=1,u=0;E.addEventListener("submit",async o=>{if(o.preventDefault(),c=o.target.elements.searchQuery.value.trim(),!!c){s=1,O(),d(),g();try{const t=await f(c,s);if(u=t.totalHits,t.hits.length===0){l.info({message:"No images found. Try another query."});return}p(t.hits),t.hits.length<15||s*15>=u?d():L()}catch{l.error({message:"Something went wrong."})}finally{b()}}});H.addEventListener("click",async()=>{s+=1,g(),d();try{const o=await f(c,s);p(o.hits);const a=document.querySelector(".gallery a").getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"}),s*15>=u?(d(),l.info({message:"We're sorry, but you've reached the end of search results."})):L()}catch{l.error({message:"Failed to load more images."})}finally{b()}});
//# sourceMappingURL=index.js.map
